### ISSUE TITLE
Usage with @FetchRequest

### ISSUE THREAD

**Issue by sleepyfran** [geor-kasapidi/HappyData#2]
Testing out the library I found out that entities that are defined as explained in the docs can't use the `@FetchRequest` attribute because the types do not conform to `NSFetchRequestResult`. From what I see in the docs `NSManagedObject` conforms to `NSFetchRequestResult`, but how can we access the inner managed object to be able to pass it?

Thanks a lot for this awesome library btw, makes working with CoreData a breeze 😄

**Comment by geor-kasapidi** [comment]
Hi, @sleepyfran, thanks for the feedback! One of the Sworm's main ideas is to hide raw coredata objects and give a developer "swifty" wrappers. To demonstrate how it's possible to avoid @FetchRequest usage, i'v made a demo for you, where used Sworm+Combine inside SwiftUI view.
[demo.zip](https://github.com/geor-kasapidi/HappyData/files/6545187/demo.zip)

P.S. sorry, documentation is in progress 🙏🏻. Writing a code is much easier for me, than write docs for it.

**Comment by sleepyfran** [comment]
Works perfectly, thanks a lot for the quick and detailed response @geor-kasapidi 😄 

No worries about the docs, honestly the library is so easy to work with that even with few docs you can get up an running in no time. Closing this as your solution works great, hopefully this can help anyone else that comes across the same until the docs are ready 😄
